### ISSUE TITLE
Getting error while installing bagisto standard

### ISSUE THREAD

**Issue by sanjana-sing** [bagisto/bagisto-standard#1]
# Bug report

### Title
Getting error while installing bagisto standard

### Issue Description
Once run the command php artisan bagisto: install, getting error in migration

### Preconditions

    1. framework Version-master
    2. Commit id-4e7866c628c7ee8b650e903777a460ebb22fd6be

### Steps to reproduce

    1. step1- download zip
    2. step2- run command "composer install" then "php artisan bagisto:install"

### Expected result
Command should run properly.

### Actual result

![Screenshot(44)](https://user-images.githubusercontent.com/47665137/81043049-221e3180-8ecf-11ea-80bb-2ce1207a86d1.png)

**Comment by vaishaliwebkul** [comment]
fixed
