### ISSUE TITLE
warning when installing composer dependencies

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-standard#3]
# Bug report

### Title
warning when installing bagisto-standard dependencies

### Issue Description
warning when installing bagisto-standard dependencies

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- download bagisto-standard zip
    2. step2- run composer install

### Actual result
  
![Screenshot from 2020-06-19 17-30-56](https://user-images.githubusercontent.com/43210406/85130572-c9beab80-b252-11ea-9533-ce4caac99203.png)

**Comment by OfficialOzioma** [comment]
I also get this warning @vaishaliwebkul please have found any solution

**Comment by vaishaliwebkul** [comment]
@OfficialOzioma 
This will not cause any issue,you can proceed further then let me know if you stuck somewhere

Thanks

**Comment by devansh-webkul** [comment]
This warning is due to the two same classes because Bagisto is added as a dependency, so it won't impact. Because the class will always hit the top level.
